### ISSUE TITLE
`rexpr` field has sometimes optional and sometimes multiple cardinality

### ISSUE THREAD

**Issue by tscholak** [lelit/pglast#56] opened 2020-06-04 12:38 UTC
Hi, Thank you for being so quick to respond with my other issue, #55!

I have observed a strange behaviour that, as a consumer of pglast parse trees, is making my work a bit more difficult.

In particular, when the `rexpr` field of the `A_Expr` constructor is present, the raw data structure returned by `parse_sql` for that field is sometimes a `list` and sometimes a `dict`. It is never a list of a single element, though.

The field therefore has a cardinality that is neither purely optional nor multiple. If the cardinality was strictly multiple, then, in the non-missing case, `parse_sql` would always return a `list` representing one or more field entries. If the cardinality was strictly optional, then, in the non-missing case, `parse_sql` would always return a `dict` representing a single field entry. All other fields that can be missing behave in either of these two ways, only `rexpr` breaks this. That makes it more difficult to deal with this field.

I am not sure if consistency concerns of this kind are in the scope of pglast because the cause may well be within postgres's parser, https://github.com/postgres/postgres/blob/master/src/backend/parser/gram.y, I haven't checked though.

**Comment by lelit** [comment] 2020-06-04 13:11
Out of curiosity, can you show a sample statement that exhibits the problem?
In general, though, I'd prefer to avoid fiddling with parser's output... but let's see.

**Comment by tscholak** [comment] 2020-06-04 13:28
Sure, no problem:

1. Example where `rexpr` is a `dict`:
```sql
SELECT count(*) FROM head WHERE age  >  56
```

```json
[
  {
    "RawStmt": {
      "stmt": {
        "SelectStmt": {
          "targetList": [
            {
              "ResTarget": {
                "val": {
                  "FuncCall": {
                    "funcname": [
                      {
                        "String": {
                          "str": "count"
                        }
                      }
                    ],
                    "agg_star": true,
                    "location": 7
                  }
                },
                "location": 7
              }
            }
          ],
          "fromClause": [
            {
              "RangeVar": {
                "relname": "head",
                "inh": true,
                "relpersistence": "p",
                "location": 21
              }
            }
          ],
          "whereClause": {
            "A_Expr": {
              "kind": 0,
              "name": [
                {
                  "String": {
                    "str": ">"
                  }
                }
              ],
              "lexpr": {
                "ColumnRef": {
                  "fields": [
                    {
                      "String": {
                        "str": "age"
                      }
                    }
                  ],
                  "location": 32
                }
              },
              "rexpr": {
                "A_Const": {
                  "val": {
                    "Integer": {
                      "ival": 56
                    }
                  },
                  "location": 40
                }
              },
              "location": 37
            }
          },
          "op": 0
        }
      }
    }
  }
]
```

2. Example where `rexpr` is a `list`:

```sql
SELECT avg(num_employees) FROM department WHERE ranking BETWEEN 10 AND 15
```

```json
[
  {
    "RawStmt": {
      "stmt": {
        "SelectStmt": {
          "targetList": [
            {
              "ResTarget": {
                "val": {
                  "FuncCall": {
                    "funcname": [
                      {
                        "String": {
                          "str": "avg"
                        }
                      }
                    ],
                    "args": [
                      {
                        "ColumnRef": {
                          "fields": [
                            {
                              "String": {
                                "str": "num_employees"
                              }
                            }
                          ],
                          "location": 11
                        }
                      }
                    ],
                    "location": 7
                  }
                },
                "location": 7
              }
            }
          ],
          "fromClause": [
            {
              "RangeVar": {
                "relname": "department",
                "inh": true,
                "relpersistence": "p",
                "location": 31
              }
            }
          ],
          "whereClause": {
            "A_Expr": {
              "kind": 11,
              "name": [
                {
                  "String": {
                    "str": "BETWEEN"
                  }
                }
              ],
              "lexpr": {
                "ColumnRef": {
                  "fields": [
                    {
                      "String": {
                        "str": "ranking"
                      }
                    }
                  ],
                  "location": 48
                }
              },
              "rexpr": [
                {
                  "A_Const": {
                    "val": {
                      "Integer": {
                        "ival": 10
                      }
                    },
                    "location": 64
                  }
                },
                {
                  "A_Const": {
                    "val": {
                      "Integer": {
                        "ival": 15
                      }
                    },
                    "location": 71
                  }
                }
              ],
              "location": 56
            }
          },
          "op": 0
        }
      }
    }
  }
]
```

> I'd prefer to avoid fiddling with parser's output

In general, I would agree. 👍

**Comment by tscholak** [comment] 2020-06-04 13:45
In the pglast code, this is solved by case matching the kind: https://github.com/aiham/pglast/blob/master/pglast/printers/dml.py#L120

**Comment by lelit** [comment] 2020-06-04 13:53
Thank you, I see. And what do you do on that? I mean, what would be your ideal way to deal with the *polymorphic* nature of that "value"?
The problem is that the "knowledge" of the "concrete shape" of the value must be obviously coded somewhere... one idea (without much thinking, really!) would be having a way to implement an higher level AST, that is, using a machinery similar to the "printers" that instead of a serialized, textual representation of the "low level" syntax would produce more usable/generic nodes...

**Comment by tscholak** [comment] 2020-06-04 13:59
> one idea (without much thinking, really!) would be having a way to implement an higher level AST

I think this is possible, but would require converting the A_Expr constructor into an A_Expr ADT with a set of constructors, one for each A_Expr kind. For instance:
```
A_Expr = A_Expr_Op(Val* name, Expr lexpr, Expr? rexpr)
       | A_Expr_Between(Val* name, Expr lexpr, Expr rexpr1, Expr rexpr2)
       | ...
```
something like that, where `Type*` means multiple cardinality, `Type?` means optional cardinality, and `Type` means single cardinality.

**Comment by lelit** [comment] 2022-06-19 13:52
I'm closing this, as there isn't much I can do, other that inventing that other layer, a big effort with uncertain advantage.

**Closed by lelit** 2022-06-19 13:52 UTC
