### ISSUE TITLE
Failed to install with pip (python 3.10.11)

### ISSUE THREAD

**Issue by abedhammoud** [lelit/pglast#121] opened 2023-05-14 18:59 UTC
when trying to install with:
```code
pip install pglast
```
I am getting the following errors:
```python
Collecting pglast
  Using cached pglast-5.1.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in c:\users\abed\miniconda3\envs\alant\lib\site-packages (from pglast) (67.7.2)
Building wheels for collected packages: pglast
  Building wheel for pglast (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pglast
      copying pglast\ast.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\error.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\keywords.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\stream.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\visitors.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\__init__.py -> build\lib.win-amd64-cpython-310\pglast
      copying pglast\__main__.py -> build\lib.win-amd64-cpython-310\pglast
      creating build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\lockdefs.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\lockoptions.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\nodes.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\parsenodes.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\pg_am.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\pg_attribute.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\pg_class.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\pg_trigger.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\primnodes.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\xml.py -> build\lib.win-amd64-cpython-310\pglast\enums
      copying pglast\enums\__init__.py -> build\lib.win-amd64-cpython-310\pglast\enums
      creating build\lib.win-amd64-cpython-310\pglast\printers
      copying pglast\printers\ddl.py -> build\lib.win-amd64-cpython-310\pglast\printers
      copying pglast\printers\dml.py -> build\lib.win-amd64-cpython-310\pglast\printers
      copying pglast\printers\sfuncs.py -> build\lib.win-amd64-cpython-310\pglast\printers
      copying pglast\printers\__init__.py -> build\lib.win-amd64-cpython-310\pglast\printers
      running build_ext
      which: no protoc-gen-c in (/cygdrive/c/Users/abed/miniconda3/envs/alant:/cygdrive/c/Users/abed/miniconda3/envs/alant/Library/mingw-w64/bin:/cygdrive/c/Users/abed/miniconda3/envs/alant/Library/usr/bin:/cygdrive/c/Users/abed/miniconda3/envs/alant/Library/bin:/cygdrive/c/Users/abed/miniconda3/envs/alant/Scripts:/cygdrive/c/Users/abed/miniconda3/envs/alant/bin:/cygdrive/c/Users/abed/miniconda3/condabin:/cygdrive/c/Users/abed/miniconda3/Scripts:/home/abed/bin:/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program Files (x86)/Boxcryptor/bin:/cygdrive/c/Program Files/Calibre2:/cygdrive/c/Program Files (x86)/Common Files/Intuit/QBPOSSDKRuntime:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files/dotnet:/cygdrive/c/Program Files/PowerShell/7:/cygdrive/c/Users/abed/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Users/abed/AppData/Local/GitHubDesktop/bin:/cygdrive/c/Users/abed/AppData/Local/Programs/Microsoft VS Code/bin:/cygdrive/c/Users/abed/AppData/Roaming/npm:/cygdrive/c/Windows/SysWow64)
      compiling src/pg_query.c
      make: cc: No such file or directory
      make: *** [Makefile:175: src/pg_query.o] Error 127
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\cygwin64\tmp\pip-install-red36q7i\pglast_564ebebda0be4ac4b4a44098c8e0e078\setup.py", line 43, in <module>
          setup(
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\abed\miniconda3\envs\alant\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-install-red36q7i\pglast_564ebebda0be4ac4b4a44098c8e0e078\setup.py", line 39, in run
          subprocess.check_call(['make', '-s', '-C', LIBPG_QUERY_DIR, 'build'])
        File "C:\Users\abed\miniconda3\envs\alant\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-s', '-C', 'libpg_query', 'build']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pglast
  Running setup.py clean for pglast
Failed to build pglast
ERROR: Could not build wheels for pglast, which is required to install pyproject.toml-based projects
(alant)

```

**Comment by lelit** [comment] 2023-05-15 05:59
This is a duplicate of #7, that I will reopen: there's little I can do on the `pglast` side, sorry.

**Closed as not planned by lelit** 2023-05-15 05:59 UTC
