### ISSUE TITLE
Install fails on mac OS with M1 chip

### ISSUE THREAD

**Issue by kino-ma** [lelit/pglast#96] opened 2021-12-17 12:16 UTC
When I tried to install `pglast` with `pip3 install pglast==1.14`, the install process errors out with the following output: 

```
# ...
    #include "port/atomics/arch-arm.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [src/pg_query_json_plpgsql.o] Error 1
#...
```

How can I install `pglast` on M1 Mac?

**Comment by lelit** [comment] 2021-12-17 15:28
Sorry, I can be of very little help, as I do not have such kind of machine around. More over, the issue seems related to the underlying `libpg_query` library: I'd try to open an issue there, I guess you are not the only one facing the problem.

**Comment by kino-ma** [comment] 2021-12-17 15:51
Thank you for your response.

Yeah, it seems to be a problem related to `pg_query`. I will watch your issue, and please tell me if there is anything I can be of help with!

**Comment by lelit** [comment] 2021-12-17 19:10
> Thank you for your response.
> 
> Yeah, it seems to be a problem related to `pg_query`. I will watch your issue, and please tell me if there is anything I can be of help with!

Please open it yourself, so you can add required details: as said, not having an M1 machine around it's difficult for me provide those.

**Comment by kino-ma** [comment] 2021-12-18 02:47
I’m sorry. I’ll do so. Thank you.

**Comment by sgreene570** [comment] 2022-02-24 16:59
Seems similar to https://github.com/pganalyze/libpg_query/issues/72, which has been resolved.

**Comment by lelit** [comment] 2022-02-24 17:30
Did you try with more recent v3 version?

**Comment by sgreene570** [comment] 2022-02-24 17:32
> Did you try with more recent v3 version?

WFM on mac m1 :)

**Comment by lelit** [comment] 2022-02-24 17:47
Does that mean "works for me"? and if so, are you suggesting to close this?

**Comment by sgreene570** [comment] 2022-02-24 18:45
> Does that mean "works for me"? and if so, are you suggesting to close this?

Yes! Works for me. If you'd like you could close out the issue since we don't have a reproducer, and let @kino-ma re-open it with more information if they chose to do so.

**Comment by lelit** [comment] 2022-02-24 19:03
Thanks!

**Closed as completed by lelit** 2022-02-24 19:03 UTC
